// Payment links


// UPI Library

const M8273551835 = [                        // User ID
    {
        upi: "gpay",                          // Account Type
        pa: "vivekratanbodh@oksbi",          // UPI ID
        pn: "VIVEK%20RATAN",                 // User Name
        mb: "8273551835",                    // Mobile Number
        aid: "uGICAgMCIpLiGLg"               // AID
    }
]

// upi://pay?pa=xyz@paytm&pn=Paytm%20Merchant&mc=abc&mode=02&orgid=000000&paytmqr=abcdefg&sign=abc+xyz/pqr/+stu

/* Payment Request [
https://    
pay.google.com/gp/v1/paymentrequest?apiVersion=2&apiVersionMinor=0      
&merchantName=YourMerchantName      
&amount=1000        
&currency=INR       
&merchantInfo=merchantId:12345678901234567890
]
*/

const UPItype = [
    {
        upi: "upi://pay?",
        gpay: "tez://upi/pay",
        phonepay: "phonepe://pay",
    }
]

const UPI = UPItype[0];

tr = "Transaction reference ID. (Business specific ID. Must be unique for each request)"

const M00 = [
    {
        pa: "Payee address or business virtual payment address (VPA)",
        pn: "Payee name or business name",
        mc: "Business retailer category code",
        url: "Transaction reference URL.",
        tid: "Transaction ID generated by the payment service provider (PSP) of the business.",
        tn: "Transaction note. It is the description appearing in the Google Pay payflow. (Maximum length is 80 characters)",
        gstBrkUp: "Break-up of Goods and Services Tax. This should follow the format: `GST:amount",
        invoiceNo: "Invoice Number. Identifier of a bill/invoice.",
        invoiceDate: "The time of invoice in RFC 3339 format. Eg, 2017-02-15T16:20:30+05:30 for IST timezone).",
        gstIn: "Business GSTIN. Goods and Services Tax Identification Number.",
    }
]

// Mobile Number
mb = document.getElementById("mob").value;

// Currency        cu: "Currency code. (This should be set in the details object instead of supportedInstruments object. Only the Indian rupee (INR) is currently supported.)",
cu = 'INR';

// Amount          am: "Transaction amount. (Up to two decimal digits are allowed. This should be set in the details object instead of the supportedInstruments object.)",
am = document.getElementById("Amount").value;


// Payment URL
// upi://pay?pa=xyz@paytm&pn=Paytm%20Merchant&mc=abc&mode=02&orgid=000000&paytmqr=abcdefg&sign=abc+xyz/pqr/+stu


// upi://pay?pa=${upiId}&pn=%20&tr=%20&am=${amount}&cu=INR

// GPAY              upi://pay?pa=vivekratanbodh@oksbi&pn=VIVEK%20RATAN&aid=uGICAgMCIpLiGLg
Gpay = UPI + "pa=" + pa + "&pn=" + pn + "&aid=" + aid;

// GPAY set Amount   upi://pay?pa=vivekratanbodh@oksbi&pn=VIVEK%20RATAN&am=10.00&cu=INR&aid=uGICAgMCIpLiGLg
GPay = "upi://pay?pa=" + pa + "&pn=" + pn + "am=" + am + "&cu=" + cu + "&aid=" + aid;

// Paytm             upi://pay?pa=8273551835@ptsbi&pn=VIVEK%20%20RATAN&mc=0000&mode=02&purpose=00&orgid=159761&cust=1246570097
Paytm = "upi://pay?pa=" + pa + "&pn=" + pn + "&mc=0000" + "&mode=02" + "&purpose=00" + "&orgid=159761" + "&cust=1246570097";

// Fampay            upi://pay?pa=vivekratan@fam&pn=VIVEK RATAN
Fampay = "upi://pay?pa=" + pa + "&pn=" + pn;


const message = "Payment Successful";
console.log(message);



// Payment QR Generator
// https://api.qrserver.com/v1/create-qr-code/?size=225x225&data=upi%3A%2F%2Fpay%3Fpa%3Dvivekratanbodh%40oksbi%26pn%3DVivek%20Ratan%26am%3D205%26tn%3Dhello%26cu%3DINR

/*
https://api.qrserver.com/v1/create-qr-code/?                    -- QR API
size=225x225                                                    -- Size of Image
&data=upi%3A%2F%2Fpay%3F                                        -- url
pa%3Dvivekratanbodh%40oksbi                                     -- UPI
%26pn%3DVivek%20Ratan                                           -- Account Name
%26am%3D205                                                     -- Amount
%26tn%3Dhello                                                   -- Message
%26cu%3DINR                                                     -- Currency
*/